/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\myProject\\sea-notes\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7cf31b21",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cf31b21").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-104af264",
    path: "/Three.js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-104af264").then(next)
    },
  },
  {
    path: "/Three.js/index.html",
    redirect: "/Three.js/"
  },
  {
    name: "v-61d8b18e",
    path: "/algorithm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61d8b18e").then(next)
    },
  },
  {
    path: "/algorithm/index.html",
    redirect: "/algorithm/"
  },
  {
    name: "v-23bc3f32",
    path: "/Three.js/home.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23bc3f32").then(next)
    },
  },
  {
    name: "v-11d2e938",
    path: "/view/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11d2e938").then(next)
    },
  },
  {
    path: "/view/index.html",
    redirect: "/view/"
  },
  {
    name: "v-1f840632",
    path: "/view/home.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f840632").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]