/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Sea-DH1 Notes",
  "description": "Sea前端笔记，常用库笔记、以及其他技术分享。",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "heroText": "Sea-DH1",
        "tagline": "LeeDH笔记",
        "actionText": "开始 →",
        "actionLink": "/view/",
        "footer": "MIT Licensed | Copyright © 2021-present Sea-DH1"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7cf31b21",
      "path": "/",
      "lastUpdated": "2021/5/6 17:45:33"
    },
    {
      "title": "WebGL",
      "frontmatter": {},
      "regularPath": "/Three.js/home.html",
      "relativePath": "Three.js/home.md",
      "key": "v-23bc3f32",
      "path": "/Three.js/home.html"
    },
    {
      "title": "Three.js",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/Three.js/",
      "relativePath": "Three.js/README.md",
      "key": "v-104af264",
      "path": "/Three.js/",
      "headers": [
        {
          "level": 2,
          "title": "什么是 web 三维",
          "slug": "什么是-web-三维"
        },
        {
          "level": 2,
          "title": "基本组成",
          "slug": "基本组成"
        },
        {
          "level": 2,
          "title": "图元",
          "slug": "图元"
        },
        {
          "level": 3,
          "title": "BoxGeometry 盒子",
          "slug": "boxgeometry-盒子"
        },
        {
          "level": 3,
          "title": "CircleGeometry 平面圆",
          "slug": "circlegeometry-平面圆"
        },
        {
          "level": 2,
          "title": "场景",
          "slug": "场景"
        },
        {
          "level": 2,
          "title": "材质",
          "slug": "材质"
        },
        {
          "level": 2,
          "title": "纹理",
          "slug": "纹理"
        },
        {
          "level": 2,
          "title": "光照",
          "slug": "光照"
        },
        {
          "level": 2,
          "title": "摄像机",
          "slug": "摄像机"
        },
        {
          "level": 2,
          "title": "阴影",
          "slug": "阴影"
        },
        {
          "level": 2,
          "title": "雾",
          "slug": "雾"
        },
        {
          "level": 2,
          "title": "渲染目标",
          "slug": "渲染目标"
        },
        {
          "level": 2,
          "title": "自定义缓冲几何体",
          "slug": "自定义缓冲几何体"
        }
      ]
    },
    {
      "title": "JavaScript数据结构与算法",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/algorithm/",
      "relativePath": "algorithm/README.md",
      "key": "v-61d8b18e",
      "path": "/algorithm/",
      "headers": [
        {
          "level": 2,
          "title": "栈",
          "slug": "栈"
        },
        {
          "level": 3,
          "title": "1、什么是栈？",
          "slug": "_1、什么是栈"
        },
        {
          "level": 3,
          "title": "2、函数调用堆栈",
          "slug": "_2、函数调用堆栈"
        },
        {
          "level": 2,
          "title": "队列",
          "slug": "队列"
        },
        {
          "level": 3,
          "title": "1、队列是什么？",
          "slug": "_1、队列是什么"
        },
        {
          "level": 3,
          "title": "2、异步队列",
          "slug": "_2、异步队列"
        }
      ],
      "lastUpdated": "2021/5/6 17:45:33"
    },
    {
      "title": "bind的实现",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/view/home.html",
      "relativePath": "view/home.md",
      "key": "v-1f840632",
      "path": "/view/home.html",
      "headers": [
        {
          "level": 3,
          "title": "bind的实现",
          "slug": "bind的实现"
        }
      ],
      "lastUpdated": "2021/5/8 19:25:54"
    },
    {
      "title": "JavaScript 基础知识",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/view/",
      "relativePath": "view/README.md",
      "key": "v-11d2e938",
      "path": "/view/",
      "headers": [
        {
          "level": 2,
          "title": "bind 的实现",
          "slug": "bind-的实现"
        },
        {
          "level": 3,
          "title": "bind 是什么？",
          "slug": "bind-是什么"
        },
        {
          "level": 3,
          "title": "返回函数的模拟实现",
          "slug": "返回函数的模拟实现"
        },
        {
          "level": 3,
          "title": "传参的模拟实现",
          "slug": "传参的模拟实现"
        },
        {
          "level": 3,
          "title": "构造函数效果的模拟实现",
          "slug": "构造函数效果的模拟实现"
        },
        {
          "level": 3,
          "title": "构造函数效果的优化实现",
          "slug": "构造函数效果的优化实现"
        },
        {
          "level": 3,
          "title": "两个小问题",
          "slug": "两个小问题"
        },
        {
          "level": 3,
          "title": "最终代码",
          "slug": "最终代码"
        },
        {
          "level": 2,
          "title": "new 操作符的原理和实现",
          "slug": "new-操作符的原理和实现"
        },
        {
          "level": 3,
          "title": "new 是什么？",
          "slug": "new-是什么"
        },
        {
          "level": 3,
          "title": "初步实现",
          "slug": "初步实现"
        },
        {
          "level": 3,
          "title": "返回值效果实现",
          "slug": "返回值效果实现"
        },
        {
          "level": 2,
          "title": "apply 和 call",
          "slug": "apply-和-call"
        },
        {
          "level": 3,
          "title": "call 是什么？",
          "slug": "call-是什么"
        },
        {
          "level": 3,
          "title": "模拟实现第一步",
          "slug": "模拟实现第一步"
        },
        {
          "level": 3,
          "title": "模拟实现第二步",
          "slug": "模拟实现第二步"
        },
        {
          "level": 3,
          "title": "模拟实现第三步",
          "slug": "模拟实现第三步"
        },
        {
          "level": 3,
          "title": "apply 的模拟实现",
          "slug": "apply-的模拟实现"
        },
        {
          "level": 2,
          "title": "原型、原型链",
          "slug": "原型、原型链"
        },
        {
          "level": 3,
          "title": "prototype",
          "slug": "prototype"
        },
        {
          "level": 3,
          "title": "__proto__",
          "slug": "proto"
        },
        {
          "level": 3,
          "title": "constructor",
          "slug": "constructor"
        },
        {
          "level": 3,
          "title": "实例与原型",
          "slug": "实例与原型"
        },
        {
          "level": 3,
          "title": "原型的原型",
          "slug": "原型的原型"
        },
        {
          "level": 3,
          "title": "原型链",
          "slug": "原型链"
        },
        {
          "level": 2,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 3,
          "title": "原型链继承",
          "slug": "原型链继承"
        },
        {
          "level": 3,
          "title": "借用构造函数（经典继承）",
          "slug": "借用构造函数-经典继承"
        },
        {
          "level": 3,
          "title": "组合继承",
          "slug": "组合继承"
        },
        {
          "level": 3,
          "title": "原型式继承",
          "slug": "原型式继承"
        },
        {
          "level": 3,
          "title": "寄生式继承",
          "slug": "寄生式继承"
        },
        {
          "level": 3,
          "title": "寄生组合式继承",
          "slug": "寄生组合式继承"
        },
        {
          "level": 2,
          "title": "闭包",
          "slug": "闭包"
        },
        {
          "level": 3,
          "title": "定义",
          "slug": "定义"
        },
        {
          "level": 3,
          "title": "分析",
          "slug": "分析"
        },
        {
          "level": 3,
          "title": "必刷题",
          "slug": "必刷题"
        },
        {
          "level": 2,
          "title": "变量提升",
          "slug": "变量提升"
        },
        {
          "level": 3,
          "title": "全局上下文",
          "slug": "全局上下文"
        },
        {
          "level": 3,
          "title": "函数上下文",
          "slug": "函数上下文"
        },
        {
          "level": 3,
          "title": "执行过程",
          "slug": "执行过程"
        },
        {
          "level": 3,
          "title": "进入执行上下文",
          "slug": "进入执行上下文"
        },
        {
          "level": 3,
          "title": "代码执行",
          "slug": "代码执行"
        },
        {
          "level": 3,
          "title": "思考题",
          "slug": "思考题"
        },
        {
          "level": 2,
          "title": "this 的指向",
          "slug": "this-的指向"
        },
        {
          "level": 3,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 3,
          "title": "Types",
          "slug": "types"
        },
        {
          "level": 3,
          "title": "Reference",
          "slug": "reference"
        },
        {
          "level": 3,
          "title": "GetValue",
          "slug": "getvalue"
        },
        {
          "level": 3,
          "title": "如何确定 this 的值",
          "slug": "如何确定-this-的值"
        },
        {
          "level": 3,
          "title": "具体分析",
          "slug": "具体分析"
        },
        {
          "level": 3,
          "title": "揭晓结果",
          "slug": "揭晓结果"
        },
        {
          "level": 3,
          "title": "补充",
          "slug": "补充-2"
        },
        {
          "level": 3,
          "title": "多说一句",
          "slug": "多说一句"
        },
        {
          "level": 2,
          "title": "立即执行函数",
          "slug": "立即执行函数"
        },
        {
          "level": 3,
          "title": "它是什么？",
          "slug": "它是什么"
        },
        {
          "level": 3,
          "title": "它的核心",
          "slug": "它的核心"
        },
        {
          "level": 3,
          "title": "函数，圆括号，错误",
          "slug": "函数-圆括号-错误"
        },
        {
          "level": 3,
          "title": "立即执行函数表达式（IIFE）",
          "slug": "立即执行函数表达式-iife"
        },
        {
          "level": 3,
          "title": "关于括号的重要笔记",
          "slug": "关于括号的重要笔记"
        },
        {
          "level": 3,
          "title": "保存闭包的状态",
          "slug": "保存闭包的状态"
        },
        {
          "level": 3,
          "title": "自执行匿名函数(\"Self-executing anonymous function\")有什么问题？",
          "slug": "自执行匿名函数-self-executing-anonymous-function-有什么问题"
        },
        {
          "level": 3,
          "title": "最后：模块模式",
          "slug": "最后-模块模式"
        },
        {
          "level": 2,
          "title": "typeof 和 instanceof",
          "slug": "typeof-和-instanceof"
        },
        {
          "level": 3,
          "title": "JavaScript 数据类型",
          "slug": "javascript-数据类型"
        },
        {
          "level": 3,
          "title": "typeof 原理",
          "slug": "typeof-原理"
        },
        {
          "level": 3,
          "title": "instanceof",
          "slug": "instanceof"
        },
        {
          "level": 3,
          "title": "JavaScrtip 原型链",
          "slug": "javascrtip-原型链"
        },
        {
          "level": 3,
          "title": "Symbol.hasInstance",
          "slug": "symbol-hasinstance"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "柯里化",
          "slug": "柯里化"
        },
        {
          "level": 3,
          "title": "定义",
          "slug": "定义-2"
        },
        {
          "level": 3,
          "title": "用途",
          "slug": "用途"
        },
        {
          "level": 3,
          "title": "第一版",
          "slug": "第一版"
        },
        {
          "level": 3,
          "title": "第二版",
          "slug": "第二版"
        },
        {
          "level": 3,
          "title": "更易懂的实现",
          "slug": "更易懂的实现"
        },
        {
          "level": 3,
          "title": "第三版",
          "slug": "第三版"
        },
        {
          "level": 3,
          "title": "写在最后",
          "slug": "写在最后"
        },
        {
          "level": 2,
          "title": "v8 垃圾回收机制",
          "slug": "v8-垃圾回收机制"
        },
        {
          "level": 2,
          "title": "浮点数精度",
          "slug": "浮点数精度"
        },
        {
          "level": 3,
          "title": "前言",
          "slug": "前言-2"
        },
        {
          "level": 3,
          "title": "数据类型",
          "slug": "数据类型"
        },
        {
          "level": 3,
          "title": "浮点数转二进制",
          "slug": "浮点数转二进制"
        },
        {
          "level": 3,
          "title": "浮点数的存储",
          "slug": "浮点数的存储"
        },
        {
          "level": 3,
          "title": "浮点数的运算",
          "slug": "浮点数的运算"
        },
        {
          "level": 3,
          "title": "其他",
          "slug": "其他"
        },
        {
          "level": 2,
          "title": "事件循环机制",
          "slug": "事件循环机制"
        },
        {
          "level": 3,
          "title": "前言",
          "slug": "前言-3"
        },
        {
          "level": 3,
          "title": "正文",
          "slug": "正文"
        },
        {
          "level": 3,
          "title": "node 环境下的事件循环机制",
          "slug": "node-环境下的事件循环机制"
        },
        {
          "level": 3,
          "title": "结尾",
          "slug": "结尾"
        },
        {
          "level": 2,
          "title": "Promise 原理",
          "slug": "promise-原理"
        },
        {
          "level": 3,
          "title": "链式调用",
          "slug": "链式调用"
        },
        {
          "level": 3,
          "title": "reject",
          "slug": "reject"
        },
        {
          "level": 3,
          "title": "异常处理",
          "slug": "异常处理"
        },
        {
          "level": 3,
          "title": "Finally 方法",
          "slug": "finally-方法"
        },
        {
          "level": 3,
          "title": "resolve 方法和 reject 方法",
          "slug": "resolve-方法和-reject-方法"
        },
        {
          "level": 3,
          "title": "Promise.all",
          "slug": "promise-all"
        },
        {
          "level": 3,
          "title": "Promise.race",
          "slug": "promise-race"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结-2"
        },
        {
          "level": 3,
          "title": "补充说明",
          "slug": "补充说明"
        },
        {
          "level": 3,
          "title": "参考资料",
          "slug": "参考资料"
        },
        {
          "level": 3,
          "title": "完整 Promise 模型",
          "slug": "完整-promise-模型"
        },
        {
          "level": 2,
          "title": "generator 原理",
          "slug": "generator-原理"
        },
        {
          "level": 3,
          "title": "Generators 简单介绍",
          "slug": "generators-简单介绍"
        },
        {
          "level": 3,
          "title": "Generators in C",
          "slug": "generators-in-c"
        },
        {
          "level": 3,
          "title": "Generators in JavaScript",
          "slug": "generators-in-javascript"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结-3"
        }
      ],
      "lastUpdated": "2021/5/25 14:24:30"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/Sea-DH1/sea-notes",
    "repoLabel": "Github",
    "lastUpdated": "最后更新时间",
    "nav": [
      {
        "text": "Javascript基础",
        "link": "/view/"
      },
      {
        "text": "Three.js",
        "link": "/Three.js/"
      },
      {
        "text": "数据结构与算法",
        "link": "/algorithm/"
      },
      {
        "text": "音乐播放器",
        "link": "https://music.nsearh.com"
      },
      {
        "text": "Examples",
        "link": "https://examples.nsearh.com/demo"
      }
    ],
    "sidebar": [
      {
        "title": "Javascript基础",
        "collapsable": true,
        "children": [
          "view/",
          "view/home"
        ]
      },
      {
        "title": "Three.js",
        "children": [
          "Three.js/"
        ]
      },
      {
        "title": "数据结构与算法",
        "children": [
          "algorithm/"
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "Sea-DH1 前端笔记",
      "description": "Sea-DH1 前端笔记，常用库笔记、以及其他技术分享。",
      "path": "/"
    }
  }
}