/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Sea-DH1 Notes",
  "description": "Sea前端笔记，常用库笔记、以及其他技术分享。",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Three.js",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/Three.js/",
      "relativePath": "Three.js/README.md",
      "key": "v-a6d4e5ca",
      "path": "/Three.js/",
      "headers": [
        {
          "level": 2,
          "title": "什么是web三维",
          "slug": "什么是web三维"
        },
        {
          "level": 2,
          "title": "基本组成",
          "slug": "基本组成"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "heroText": "Sea-DH1",
        "tagline": "LeeDH笔记",
        "actionText": "开始 →",
        "actionLink": "/view/",
        "footer": "MIT Licensed | Copyright © 2021-present Sea-DH1"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b60cb0b",
      "path": "/",
      "lastUpdated": "2021/5/6 下午5:45:33"
    },
    {
      "title": "前端基础",
      "frontmatter": {
        "sidebar": "auto",
        "sidebarDepth": 2
      },
      "regularPath": "/view/",
      "relativePath": "view/README.md",
      "key": "v-19dcde9b",
      "path": "/view/",
      "headers": [
        {
          "level": 2,
          "title": "JavaScript基础知识",
          "slug": "javascript基础知识"
        },
        {
          "level": 3,
          "title": "bind的实现",
          "slug": "bind的实现"
        },
        {
          "level": 3,
          "title": "new操作符的原理和实现",
          "slug": "new操作符的原理和实现"
        },
        {
          "level": 3,
          "title": "apply和call",
          "slug": "apply和call"
        },
        {
          "level": 3,
          "title": "原型、原型链",
          "slug": "原型、原型链"
        },
        {
          "level": 3,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 3,
          "title": "闭包",
          "slug": "闭包"
        },
        {
          "level": 3,
          "title": "变量提升",
          "slug": "变量提升"
        },
        {
          "level": 3,
          "title": "this的指向",
          "slug": "this的指向"
        },
        {
          "level": 3,
          "title": "立即执行函数",
          "slug": "立即执行函数"
        },
        {
          "level": 3,
          "title": "instanceof原理",
          "slug": "instanceof原理"
        },
        {
          "level": 3,
          "title": "柯里化",
          "slug": "柯里化"
        },
        {
          "level": 3,
          "title": "v8垃圾回收机制",
          "slug": "v8垃圾回收机制"
        },
        {
          "level": 3,
          "title": "浮点数精度",
          "slug": "浮点数精度"
        },
        {
          "level": 3,
          "title": "new操作符",
          "slug": "new操作符"
        },
        {
          "level": 3,
          "title": "事件循环机制",
          "slug": "事件循环机制"
        },
        {
          "level": 3,
          "title": "promise原理",
          "slug": "promise原理"
        },
        {
          "level": 3,
          "title": "generator原理",
          "slug": "generator原理"
        }
      ],
      "lastUpdated": "2021/5/7 下午12:02:25"
    },
    {
      "title": "home",
      "frontmatter": {},
      "regularPath": "/view/home.html",
      "relativePath": "view/home.md",
      "key": "v-d4b62460",
      "path": "/view/home.html",
      "lastUpdated": "2021/5/1 上午6:01:40"
    },
    {
      "title": "JavaScript数据结构与算法",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/algorithm/",
      "relativePath": "algorithm/README.md",
      "key": "v-f6f3be6a",
      "path": "/algorithm/",
      "headers": [
        {
          "level": 2,
          "title": "栈",
          "slug": "栈"
        },
        {
          "level": 3,
          "title": "1、什么是栈？",
          "slug": "_1、什么是栈"
        },
        {
          "level": 3,
          "title": "2、函数调用堆栈",
          "slug": "_2、函数调用堆栈"
        },
        {
          "level": 2,
          "title": "队列",
          "slug": "队列"
        },
        {
          "level": 3,
          "title": "1、队列是什么？",
          "slug": "_1、队列是什么"
        },
        {
          "level": 3,
          "title": "2、异步队列",
          "slug": "_2、异步队列"
        }
      ],
      "lastUpdated": "2021/5/6 下午5:45:33"
    },
    {
      "title": "WebGL",
      "frontmatter": {},
      "regularPath": "/Three.js/home.html",
      "relativePath": "Three.js/home.md",
      "key": "v-fce5cc60",
      "path": "/Three.js/home.html"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/Sea-DH1/sea-notes",
    "repoLabel": "Github",
    "lastUpdated": "最后更新时间",
    "nav": [
      {
        "text": "Javascript基础",
        "link": "/view/"
      },
      {
        "text": "Three.js",
        "link": "/Three.js/"
      },
      {
        "text": "数据结构与算法",
        "link": "/algorithm/"
      },
      {
        "text": "音乐播放器",
        "link": "https://music.nsearh.com"
      },
      {
        "text": "Examples",
        "link": "https://blog.nsearh.com"
      }
    ],
    "sidebar": [
      {
        "title": "Javascript基础",
        "children": [
          "view/",
          "view/home"
        ]
      },
      {
        "title": "Three.js",
        "children": [
          "Three.js/"
        ]
      },
      {
        "title": "数据结构与算法",
        "children": [
          "algorithm/"
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "Sea-DH1 前端笔记",
      "description": "Sea-DH1 前端笔记，常用库笔记、以及其他技术分享。",
      "path": "/"
    }
  }
}