/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Sea-DH1 Notes",
  "description": "Sea前端笔记，常用库笔记、以及其他技术分享。",
  "base": "/sea-notes/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "heroText": "Sea-DH1",
        "tagline": "LeeDH笔记",
        "actionText": "开始 →",
        "actionLink": "/view/",
        "features": [
          {
            "title": "前端技术"
          },
          {
            "title": "Vue / React"
          },
          {
            "title": "three.js"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-present Sea-DH1"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3b60cb0b",
      "path": "/",
      "lastUpdated": "2021/4/30 上午1:56:32"
    },
    {
      "title": "前端基础",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/view/",
      "relativePath": "view/README.md",
      "key": "v-19dcde9b",
      "path": "/view/",
      "headers": [
        {
          "level": 2,
          "title": "JavaScript基础知识",
          "slug": "javascript基础知识"
        }
      ],
      "lastUpdated": "2021/4/30 上午1:56:32"
    },
    {
      "title": "home",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/view/home.html",
      "relativePath": "view/home.md",
      "key": "v-d4b62460",
      "path": "/view/home.html"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/Sea-DH1/sea-notes",
    "repoLabel": "Github",
    "lastUpdated": "最后更新时间",
    "nav": [
      {
        "text": "音乐播放器",
        "items": [
          {
            "text": "移动端",
            "link": "https://music.nsearh.com"
          }
        ]
      },
      {
        "text": "Blog",
        "link": "https://blog.nsearh.com"
      }
    ],
    "sidebar": [
      {
        "title": "Javascript基础",
        "collapsable": false,
        "children": [
          "view/",
          "view/home"
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "Sea-DH1 前端笔记",
      "description": "Sea-DH1 前端笔记，常用库笔记、以及其他技术分享。",
      "path": "/"
    }
  }
}